2024-02-05 11:35:55 - test - Error al mostrar la lista de bibliotecas en el metodo 'lista_biblioteca' [revisar url y api plex]: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000242D073CDC0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
-----------------------------------------------------
2024-02-05 11:41:53 - test - Error al mostrar la lista de bibliotecas en el metodo 'lista_biblioteca' [revisar url y api plex]: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001651A43CF70>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
-----------------------------------------------------
2024-02-05 11:42:03 - test - Error al mostrar la lista de bibliotecas en el metodo 'lista_biblioteca' [revisar url y api plex]: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001651A483970>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
-----------------------------------------------------
2024-02-05 11:45:07 - test - Error al crear cuenta plex en el metodo 'crear_cuenta_plex' [revisar url y api plex]: 'dict' object has no attribute 'append'
-----------------------------------------------------
2024-02-05 11:46:20 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 11:47:00 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 11:47:46 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 11:53:36 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:20:09 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:21:09 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:21:35 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:21:55 - GLOBAL - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca_route_global' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:22:56 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:23:56 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
2024-02-05 12:24:57 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
05-02-2024 12:25:10 - GLOBAL - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca_route_global' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
05-02-2024 12:25:25 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: (401) unauthorized; http://192.168.1.2:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
-----------------------------------------------------
06-02-2024 08:29:26 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EBF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:30:01 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DD810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:31:03 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E88B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:32:09 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E8730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:33:11 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E93F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:33:57 - kely49 - Error al eliminar invitacion en el metodo 'eliminar_acceso_biblioteca' sobre el usuario asfasfas@asdfafasfsaf.com [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EA4A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:34:15 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DFF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:35:18 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DD990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:36:20 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DC8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:37:22 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DE290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:38:25 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DDAB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:39:27 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DEE60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:40:30 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DD810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:41:32 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DCD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:42:34 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DD600>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:43:37 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DF400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:44:39 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E9900>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:45:41 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DF610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:46:44 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EB0A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:47:46 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DFAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:48:48 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EBAF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:49:51 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DC520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:50:53 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EB490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:51:55 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DC5E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:52:58 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E83D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:54:00 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DEF20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:55:02 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E8640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:56:05 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB1F524D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:57:07 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DF3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:58:09 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DEE90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 08:59:12 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DDF00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:00:14 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DC2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:01:16 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DE0E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:02:19 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DDFC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:03:21 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DE800>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:04:23 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DE770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:05:26 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DFAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:06:28 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EA170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:07:30 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22DE830>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:08:33 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E95A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:09:35 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EA1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:10:37 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EACB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:11:40 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EB3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:12:42 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E9DE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:13:44 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EA380>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:14:47 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22EA7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:15:49 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E9A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:16:51 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E9090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
06-02-2024 09:17:54 - GLOBAL - Error al detener la sesion del usuario asfasfas@asdfafasfsaf.com 'detener_sesiones_excedentes_global' [revisar url y api plex]: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //79.116.29.47:32400/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BB22E81C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-----------------------------------------------------
